#!/bin/bash

ANSIBLE_REPO="${ANSIBLE_REPO:-ppa:ansible/ansible}";
PROJECT_DIR="$(dirname $0)/..";
PLATFORM="${DOTFILES_PLATFORM:-ubuntu}";
PYTHON_VER='3.6'
LOG_LEVEL="${LOG_LEVEL:-INFO}";

read -r -d '' INSTALL_USAGE <<'EOF'
install-ansible
[summary]
Command for installing ansible.

[description]
Install the ansible and the required python binaries for the specified $PLATFORM.

Must be run as root.

[usage]
- View this help message:
install-ansible -h

- Execute with a log level of DEBUG:
LOG_LEVEL=debug install-ansible 
EOF

. "${PROJECT_DIR}/.logging";

main() {
  while (( "$#" )); do
    case "$1" in
      '-h' | '--help')
        echo "${INSTALL_USAGE}";
        exit 0;
        ;;
      *)
    esac
  done

  case "${PLATFORM}" in
    'ubuntu')
      apt update;
      apt install 'software-properties-common';
      apt-add-repository --yes --update "${ANSIBLE_REPO}";
      apt-get install -y "python${PYTHON_VER}" 'ansible';
      ;;
    *)
      log_debug "unsupported platform, ${PLATFORM}";
      exit 1;
      ;;
  esac

  echo "done"; 
}

main "$@";
